### ISSUE TITLE
Palabra mal escrita "Inutilisable"

### ISSUE THREAD

**Issue by DanielVanegas11** [UDEA-Esp-Analitica-y-Ciencia-de-Datos/EACD-01-FUNDAMENTOS#13]
Existe un error ortográfico en https://github.com/UDEA-Esp-Analitica-y-Ciencia-de-Datos/EACD-01-FUNDAMENTOS/blob/master/05%20-%20Funciones%20y%20Lambdas.ipynb en el siguiente texto:

"Es peligroso usar funciones de esta manera porque múltiples funciones pueden modificar la variable de formas diferentes, volviéndola INUTILISABLE para las otras. Además, es más ineficiente trabajar con variables globales que con variables locales"

La forma correcta es "Inutilizable"

**Comment by srcolinas** [comment]
@DanielVanegas11 puedes hacer un PR?
