### ISSUE TITLE
Letra faltante

### ISSUE THREAD

**Issue by adrianx30** [UDEA-Esp-Analitica-y-Ciencia-de-Datos/EACD-01-FUNDAMENTOS#3]
https://github.com/UDEA-Esp-Analitica-y-Ciencia-de-Datos/EACD-01-FUNDAMENTOS/blob/master/01%20-%20Tipos%20de%20datos%20y%20operadores.ipynb

Dentro de la explicación del quinto bloque de ejecución, falta la "r" dentro del parentesis para que diga "letra"

**Comment by srcolinas** [comment]
Muchas gracias! Por favor has un PR con la corrección para obtener tu bonificación
