### ISSUE TITLE
Palabra mal escrita "Progamación"

### ISSUE THREAD

**Issue by DanielVanegas11** [UDEA-Esp-Analitica-y-Ciencia-de-Datos/EACD-01-FUNDAMENTOS#5]
https://github.com/UDEA-Esp-Analitica-y-Ciencia-de-Datos/EACD-01-FUNDAMENTOS

El error se encuentra en el siguiente título "Fundamentos de progamación para ciencia de datos"

**Comment by srcolinas** [comment]
@DanielVanegas11  puedes hacer un PR?
